### ISSUE TITLE
update form 

### ISSUE THREAD

**Issue by icusick** [icusick/InstrctrCr33pr#1]
Hi Anna! 

I know this is really basic and I should know already how to do this but I'm having trouble with the update form. Right now I have the date as a link which takes you to a page where you can input the date and the amount of coffee and it will update the database. What I would like for it to do is take you to the update page AND for the update page to already know which database item you're trying to update. In ruby apps we would squids the id into the link and send over the params in the server's get request. I'm not really sure how to do that with node. If you have a few minutes could I sit down with you? Let me know! If not, I can leave it as is. Thanks! 

Isabel

**Comment by annarankin** [comment]
@sungchoi @phlco Hey, if you're free sooner than I am, could you check out Isabel's issue?

**Comment by phlco** [comment]
Hey Isabel! Pre-propulating a form is pretty standard across any stack.

You just need to fill in the `value` attribute. 

```
<input type="text" value="this will be the value in the input field" name="dog_name">
```

So if you're trying to do it with node and mongo you just need to find the values and then fill them in

Here's some pseudo code I made up. 

```
app.get('/update_form', function(req, res){
  db.collection('things').findOne(function(err, results){
    res.render('template', {thing: results})
  });
})
```

```
<input type="text" value="<%= thing.value_from_server %>" name="dog_name">
```

Does that help?

**Comment by icusick** [comment]
i think so, let me try it out. thanks!

**Comment by icusick** [comment]
I've tried a few things, nothing is working. If anyone gets time, could we meet? I will be so quick!

**Comment by phlco** [comment]
sure i'll come find you!
